//This is auto generated by feature.py, don't modify.
package com.journeyOS;

public final class JosFeature {

    //  jos feature default
    public static final int JOS_FEATURE_DEFAULT = 1;

    //  jos device
    public static final String JOS_FEATURE_DEVICE = "lemonadep";

    //  jos ai service
    public static final boolean JOS_FEATURE_AI_SERVICE = false;


}
