# This is auto generated by feature.py, don't modify.
#ifndef __PLATFORM_FEATURE__
#define __PLATFORM_FEATURE__

#  jos feature default
#define JOS_FEATURE_DEFAULT 1

#  jos device
#define JOS_FEATURE_DEVICE lemonadep

#  jos ai service
#define JOS_FEATURE_AI_SERVICE 0

#endif // __PLATFORM_FEATURE__
